env:
  - ANSIBLE_VERSION='ansible>=2.0,<2.1'
  - ANSIBLE_VERSION='ansible>=2.1,<2.2'
  - ANSIBLE_VERSION='ansible>=2.2,<2.3'
  - ANSIBLE_VERSION='ansible>=2.3,<2.4'
  - ANSIBLE_VERSION='ansible>=2.4,<2.5'

language: python

install:
  - pip install "$ANSIBLE_VERSION"

script:
  - ansible-playbook --syntax-check tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
